[package]
name = "gluster"
description = "A library to interface with Gluster's CLI.  This is being leveraged by a Juju charm to manage a Gluster deployment"
documentation = "https://cholcombe973.github.io/Gluster/gluster/index.html"
version = "0.1.7"
authors = ["Chris Holcombe <xfactor973@gmail.com>"]
repository = "https://github.com/cholcombe973/Gluster"
license = "MIT"

[dependencies]
byteorder = "*"
log = "*"
regex = "*"
unix_socket = "*"
uuid = "*"
