[package]
name = "gluster"
version = "0.1.0"
authors = ["Chris Holcombe <xfactor973@gmail.com>"]
repository = "https://github.com/cholcombe973/Gluster"
license = "MIT"

[dependencies.uuid]
version = "*"

[dependencies.regex]
version = "*"
