[package]
name = "gluster"
description = "A library to interface with Gluster's CLI.  This is being leveraged by a Juju charm to manage a Gluster deployment"
documentation = "https://cholcombe973.github.io/Gluster/gluster/index.html"
version = "0.3.2"
authors = ["Chris Holcombe <xfactor973@gmail.com>"]
repository = "https://github.com/cholcombe973/Gluster"
license = "MIT"

[dependencies]
byteorder = "0.4.2"
log = "0.3.5"
regex = "0.1.53"
unix_socket = "0.5.0"
uuid = "0.1.18"
